---
title: "Lily_SoilType_By_Site"
output: html_document
date: "2024-05-28"
---
Load Packages
```{r}
library(mgcv)
library(nlme)
library(permute)
library(lattice)
library(vegan)
library(ggplot2)
library(tidyverse)
library(readxl)
library(RColorBrewer)
library(ecole)


set.seed(13)
```

# Ricketts
Load in Data
```{r}
ASV_R1 <- read.csv("~/ASVtable_RickettsSite1.csv", header=TRUE, row.names=1)
ASV_R2 <- read.csv("~/ASVtable_RickettsSite2.csv", header=TRUE, row.names=1)
metadata_R1<- read.csv("~/Lily_Metadata_RickettsSite1.csv")
metadata_R2<- read.csv("~/Lily_Metadata_RickettsSite2.csv")
```

Create a dissimilarity matrix
```{r}
rhizosbulk_dis_R1 <- avgdist(ASV_R1,sample=4000, dmethod = "bray")
rhizosbulk_dis_R2 <- avgdist(ASV_R2,sample=4000, dmethod = "bray")
```

## Permanovas
### Site 1
```{r}
perm_soiltype_R1 <-adonis2(rhizosbulk_dis_R1~as.factor(metadata_R1$Depth), data=metadata_R1, permutations=9999)
perm_soiltype_R1 #Viewing data
```

```{r}
soiltype_pvalue_table_R1 <- permanova_pairwise(rhizosbulk_dis_R1, metadata_R1$Depth, permutations=9999 ,padj = "bonferroni")
soiltype_pvalue_table_R1
```

### Site 2
```{r}
perm_soiltype_R2 <-adonis2(rhizosbulk_dis_R2~as.factor(metadata_R2$Depth), data=metadata_R2, permutations=9999)
perm_soiltype_R2 #Viewing data
```

```{r}
soiltype_pvalue_table_R2 <- permanova_pairwise(rhizosbulk_dis_R2, metadata_R2$Depth, permutations=9999 ,padj = "bonferroni")
soiltype_pvalue_table_R2
```

## MDS
## Site 1
```{r}
nmds_R1 <- metaMDS(rhizosbulk_dis_R1) %>% scores() %>% as_tibble(rownames = "Sample")
plot(nmds_R1)

stress_value_R1 <- metaMDS(rhizosbulk_dis_R1)$stress
stress_value_R1
```

```{r}
metadata_nmds_R1 <- inner_join(metadata_R1, nmds_R1)
plot(metadata_nmds_R1)
```

```{r}
metadata_nmds_R1 %>% ggplot(aes(x=NMDS1,y=NMDS2, color=Depth)) + geom_point(shape = 19, size=3) + 
  coord_fixed() + 
  scale_color_manual(name=NULL, 
                     values = c("violet", "blue", "orange"), 
                     breaks = c("Bulk", "Proximal", "Rhizosphere"), 
                     labels = c("Bulk", "Proximal", "Rhizosphere")) +
  labs(title = "Microbial Communities Separated by Soil type", x = "Dimension 1", y = "Dimension 2") + 
  theme_classic() + theme(plot.title = element_text(size=15), plot.title.position = "plot", legend.key.size = unit(20,"pt"),
                          legend.text= element_text(size=16),
                          axis.title.y = element_text(size=20), axis.title.x = element_text(size=20),
                          axis.text.x = element_text(size=16), axis.text.y = element_text(size=16), legend.position = "top")
```

## Site 2
```{r}
nmds_R2 <- metaMDS(rhizosbulk_dis_R2) %>% scores() %>% as_tibble(rownames = "Sample")
plot(nmds_R2)

stress_value_R2 <- metaMDS(rhizosbulk_dis_R2)$stress
stress_value_R2
```

```{r}
metadata_nmds_R2 <- inner_join(metadata_R2, nmds_R2)
plot(metadata_nmds_R2)
```

```{r}
metadata_nmds_R2 %>% ggplot(aes(x=NMDS1,y=NMDS2, color=Depth)) + geom_point(shape = 19, size=3) + 
  coord_fixed() + 
  scale_color_manual(name=NULL, 
                     values = c("violet", "blue", "orange"), 
                     breaks = c("Bulk", "Proximal", "Rhizosphere"), 
                     labels = c("Bulk", "Proximal", "Rhizosphere")) +
  labs(title = "Microbial Communities Separated by Soil type", x = "Dimension 1", y = "Dimension 2") + 
  theme_classic() + theme(plot.title = element_text(size=15), plot.title.position = "plot", legend.key.size = unit(20,"pt"),
                          legend.text= element_text(size=16),
                          axis.title.y = element_text(size=20), axis.title.x = element_text(size=20),
                          axis.text.x = element_text(size=16), axis.text.y = element_text(size=16), legend.position = "top")
```
# Nesco
Load in Data
```{r}
ASV_N1 <- read.csv("~/ASVtable_N1.csv", header=TRUE, row.names=1)
ASV_N3 <- read.csv("~/ASVtable_N3.csv", header=TRUE, row.names=1)
metadata_N1<- read.csv("~/Lily_Metadata_N1.csv")
metadata_N3<- read.csv("~/Lily_Metadata_N3.csv")
```

Create a dissimilarity matrix
```{r}
rhizosbulk_dis_N1 <- avgdist(ASV_N1,sample=4000, dmethod = "bray")
rhizosbulk_dis_N3 <- avgdist(ASV_N3,sample=4000, dmethod = "bray")
```

## Permanovas
### Site 1
```{r}
perm_soiltype_N1 <-adonis2(rhizosbulk_dis_N1~as.factor(metadata_N1$Depth), data=metadata_N1, permutations=9999)
perm_soiltype_N1 #Viewing data
```

```{r}
soiltype_pvalue_table_N1 <- permanova_pairwise(rhizosbulk_dis_N1, metadata_N1$Depth, permutations=9999 ,padj = "bonferroni")
soiltype_pvalue_table_N1
```

### Site 2
```{r}
perm_soiltype_N3 <-adonis2(rhizosbulk_dis_N3~as.factor(metadata_N3$Depth), data=metadata_N3, permutations=9999)
perm_soiltype_N3 #Viewing data
```

```{r}
soiltype_pvalue_table_N3 <- permanova_pairwise(rhizosbulk_dis_N3, metadata_N3$Depth, permutations=9999 ,padj = "bonferroni")
soiltype_pvalue_table_N3
```

## MDS
## Site 1
```{r}
nmds_N1 <- metaMDS(rhizosbulk_dis_N1) %>% scores() %>% as_tibble(rownames = "Sample")
plot(nmds_N1)

stress_value_N1 <- metaMDS(rhizosbulk_dis_N1)$stress
stress_value_N1
```

```{r}
metadata_nmds_N1 <- inner_join(metadata_N1, nmds_N1)
plot(metadata_nmds_N1)
```

```{r}
metadata_nmds_N1 %>% ggplot(aes(x=NMDS1,y=NMDS2, color=Depth)) + geom_point(shape = 19, size=3) + 
  coord_fixed() + 
  scale_color_manual(name=NULL, 
                     values = c("violet", "blue", "orange"), 
                     breaks = c("Bulk", "Proximal", "Rhizosphere"), 
                     labels = c("Bulk", "Proximal", "Rhizosphere")) +
  labs(title = "Microbial Communities Separated by Soil type", x = "Dimension 1", y = "Dimension 2") + 
  theme_classic() + theme(plot.title = element_text(size=15), plot.title.position = "plot", legend.key.size = unit(20,"pt"),
                          legend.text= element_text(size=16),
                          axis.title.y = element_text(size=20), axis.title.x = element_text(size=20),
                          axis.text.x = element_text(size=16), axis.text.y = element_text(size=16), legend.position = "top")
```

## Site 3
```{r}
nmds_N3 <- metaMDS(rhizosbulk_dis_N3) %>% scores() %>% as_tibble(rownames = "Sample")
plot(nmds_N3)

stress_value_N3 <- metaMDS(rhizosbulk_dis_N3)$stress
stress_value_N3
```

```{r}
metadata_nmds_N3 <- inner_join(metadata_N3, nmds_N3)
plot(metadata_nmds_N3)
```

```{r}
metadata_nmds_N3 %>% ggplot(aes(x=NMDS1,y=NMDS2, color=Depth)) + geom_point(shape = 19, size=3) + 
  coord_fixed() + 
  scale_color_manual(name=NULL, 
                     values = c("violet", "blue", "orange"), 
                     breaks = c("Bulk", "Proximal", "Rhizosphere"), 
                     labels = c("Bulk", "Proximal", "Rhizosphere")) +
  labs(title = "Microbial Communities Separated by Soil type", x = "Dimension 1", y = "Dimension 2") + 
  theme_classic() + theme(plot.title = element_text(size=15), plot.title.position = "plot", legend.key.size = unit(20,"pt"),
                          legend.text= element_text(size=16),
                          axis.title.y = element_text(size=20), axis.title.x = element_text(size=20),
                          axis.text.x = element_text(size=16), axis.text.y = element_text(size=16), legend.position = "top")
```
